/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pop2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static pop2.Concerts.txtConcertName;
import static pop2.Concerts.txtDateTime;
import static pop2.Concerts.txtLocation;
import static pop2.Concerts.txtNoOfSeats;
import static pop2.Concerts.txtOrganizer;
import static pop2.Concerts.txtTicketPrice;

/**
 *
 * @author Admin
 */
public class ConfirmBooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfirmBooking
     */
    public ConfirmBooking() {
        initComponents();
        Concerts();
    }

    
    
    public void Concerts(){
        
         DefaultTableModel table = new DefaultTableModel();
    
    table.addColumn("BookID");
    table.addColumn("User");
    table.addColumn("Concert Name");
    table.addColumn("Date Time");
    table.addColumn("Location");
    table.addColumn("Organizer");
    table.addColumn("No Of Seats");
    table.addColumn("Ticket Price");
    table.addColumn("Booked Seats");
    
   
    try(Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Rhythm","root",""))
    {
        
       String sql = "SELECT * FROM booking";
        
       PreparedStatement st = conn.prepareStatement(sql);
        
             ResultSet rs = (ResultSet) st.executeQuery();
             // rs =(OracleResultSet) pst.executeQuery();
        
        //ResultSet R = S.executeQuery(sql);
        
        while(rs.next()){
            table.addRow(new Object[]{
              rs.getString(1),
                rs.getString(2),
               rs.getString(3),
                rs.getString(4),
                rs.getString(5),
               rs.getString(6),
               rs.getString(7),
               rs.getString(8),
                rs.getString(9)
               
               
            });
        }
        Confirm.setModel(table);
        Confirm.setShowHorizontalLines(true); 
       
        
       
        
        
        
        
        
        
    }catch(Exception e){
        
    }
    
        
        
    
    
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ConcertTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Location = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Organizer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Seats = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Ticket = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Confirm = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        BookID = new javax.swing.JTextField();
        BookSeat = new javax.swing.JTextField();

        ConcertTable.setBackground(new java.awt.Color(55, 38, 92));
        ConcertTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConcertTable.setForeground(new java.awt.Color(255, 255, 255));
        ConcertTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ConcertID", "Concert Name", "Date Time", "Location", "Oragnizer", "No. of Seats", "Ticket Price"
            }
        ));
        ConcertTable.setRowHeight(50);
        ConcertTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcertTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ConcertTable);

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Confirm Booking");

        jLabel5.setText("Date/Time");

        jLabel4.setText("Concert Name");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        jLabel6.setText("Location");

        jLabel7.setText("Organizer");

        Organizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganizerActionPerformed(evt);
            }
        });

        jLabel9.setText("No.of Seats");

        jLabel10.setText("Ticket Price");

        Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketActionPerformed(evt);
            }
        });

        jLabel11.setText("Booked Seats");

        jLabel12.setText("User");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Confirm Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Confirm.setBackground(new java.awt.Color(55, 38, 92));
        Confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Confirm.setForeground(new java.awt.Color(255, 255, 255));
        Confirm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Concert Name", "Date Time", "Location", "Oragnizer", "No Of Seats", "Ticket Price"
            }
        ));
        Confirm.setRowHeight(50);
        Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Confirm);

        jLabel8.setText("BookID");

        BookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Name)
                                    .addComponent(Location)
                                    .addComponent(Organizer)
                                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookID)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Seats)
                                        .addComponent(Ticket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BookSeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Organizer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(BookSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConcertTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcertTableMouseClicked

      
    }//GEN-LAST:event_ConcertTableMouseClicked

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void OrganizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganizerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrganizerActionPerformed

    private void TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
        try{

            Class.forName("com.mysql.jdbc.Driver");
            //Connection conn = DriverManager.getConnection(myUrl, "root", "");
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Rhythm","root","")) {
                String query = "INSERT INTO confirmbooking (BookID,User,ConcertName,ConcertDate,ConcertLocation,ConcertOrganizer,NoOfSeats,TicketPrice,BookedSeats)" + "values(?,?,?,?,?,?,?,?,?)";

                PreparedStatement st = conn.prepareStatement(query);

                st.setString(1,BookID.getText());

                st.setString(2,User.getText());

                st.setString(3,Name.getText());

                st.setString(4,Date.getText());

                st.setString(5,Location.getText());

                st.setString(6,Organizer.getText());

                st.setString(7,Seats.getText());

                st.setString(8,Ticket.getText());
                
                st.setString(9,BookSeat.getText());

                st.execute();
            }

            JOptionPane.showMessageDialog(null,"Confirm Booking Successful.Enjoy using Rhythm for more concerts.");

            Concerts();

            InvoiceGen yu=new InvoiceGen();
            yu.setVisible(true);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmMouseClicked
    DefaultTableModel model = (DefaultTableModel)Confirm.getModel();

        
        int selectedRowIndex = Confirm.getSelectedRow();

        BookID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        User.setText(model.getValueAt(selectedRowIndex, 1).toString());
        Name.setText(model.getValueAt(selectedRowIndex, 2).toString());
        Date.setText(model.getValueAt(selectedRowIndex, 3).toString());
        Location.setText(model.getValueAt(selectedRowIndex, 4).toString());
        Organizer.setText(model.getValueAt(selectedRowIndex, 5).toString());
        Seats.setText(model.getValueAt(selectedRowIndex, 6).toString());
        Ticket.setText(model.getValueAt(selectedRowIndex, 7).toString());
        
        BookSeat.setText(model.getValueAt(selectedRowIndex, 8).toString());        
       
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ConfirmMouseClicked

    private void BookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField BookID;
    public static javax.swing.JTextField BookSeat;
    private javax.swing.JTable ConcertTable;
    private javax.swing.JTable Confirm;
    public static javax.swing.JTextField Date;
    public static javax.swing.JTextField Location;
    public static javax.swing.JTextField Name;
    public static javax.swing.JTextField Organizer;
    public static javax.swing.JTextField Seats;
    public static javax.swing.JTextField Ticket;
    public static javax.swing.JTextField User;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
